services:
  postgres:
    image: postgres:16-alpine
    container_name: themis_race_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: themis
      POSTGRES_PASSWORD: themis_secret
      POSTGRES_DB: themis_race_tracker
    ports:
      - "5433:5432"
    volumes:
      - themis_pg_data:/var/lib/postgresql/data

volumes:
  themis_pg_data:
